[phases.setup]
nixPkgs = ["nodejs_20", "corepack"]
cmds = ["corepack enable", "corepack prepare yarn@4.10.3 --activate"]

[phases.install]
cmds = ["yarn install --immutable"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start"
